//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://docs.oasis-open.org/odata/ns/edm}GExpression" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://docs.oasis-open.org/odata/ns/edm}GInlineExpressions"/>
 *       &lt;attribute name="Term" use="required" type="{http://docs.oasis-open.org/odata/ns/edm}TQualifiedName" />
 *       &lt;attribute name="Qualifier" type="{http://docs.oasis-open.org/odata/ns/edm}TSimpleIdentifier" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annotation",
    "binaryElement",
    "boolElement",
    "dateElement",
    "dateTimeOffsetElement",
    "decimalElement",
    "durationElement",
    "enumMemberElement",
    "floatElement",
    "guidElement",
    "intElement",
    "stringElement",
    "timeOfDayElement",
    "annotationPathElement",
    "apply",
    "cast",
    "collection",
    "_if",
    "eq",
    "ne",
    "ge",
    "gt",
    "le",
    "lt",
    "and",
    "or",
    "not",
    "isOf",
    "labeledElement",
    "labeledElementReference",
    "_null",
    "navigationPropertyPathElement",
    "pathElement",
    "propertyPathElement",
    "record",
    "urlRefElement"
})
@XmlRootElement(name = "Annotation")
public class Annotation {

    @XmlElement(name = "Annotation")
    protected List<Annotation> annotation;
    @XmlElement(name = "Binary")
    protected TBinaryConstantExpression binaryElement;
    @XmlElement(name = "Bool")
    protected TBoolConstantExpression boolElement;
    @XmlElement(name = "Date")
    protected TDateConstantExpression dateElement;
    @XmlElement(name = "DateTimeOffset")
    protected TDateTimeOffsetConstantExpression dateTimeOffsetElement;
    @XmlElement(name = "Decimal")
    protected TDecimalConstantExpression decimalElement;
    @XmlElement(name = "Duration")
    protected TDurationConstantExpression durationElement;
    @XmlList
    @XmlElement(name = "EnumMember")
    protected List<String> enumMemberElement;
    @XmlElement(name = "Float")
    protected TFloatConstantExpression floatElement;
    @XmlElement(name = "Guid")
    protected TGuidConstantExpression guidElement;
    @XmlElement(name = "Int")
    protected TIntConstantExpression intElement;
    @XmlElement(name = "String")
    protected TStringConstantExpression stringElement;
    @XmlElement(name = "TimeOfDay")
    protected TTimeOfDayConstantExpression timeOfDayElement;
    @XmlElement(name = "AnnotationPath")
    protected TPathExpression annotationPathElement;
    @XmlElement(name = "Apply")
    protected TApplyExpression apply;
    @XmlElement(name = "Cast")
    protected TCastOrIsOfExpression cast;
    @XmlElement(name = "Collection")
    protected TCollectionExpression collection;
    @XmlElement(name = "If")
    protected TIfExpression _if;
    @XmlElement(name = "Eq")
    protected TTwoChildrenExpression eq;
    @XmlElement(name = "Ne")
    protected TTwoChildrenExpression ne;
    @XmlElement(name = "Ge")
    protected TTwoChildrenExpression ge;
    @XmlElement(name = "Gt")
    protected TTwoChildrenExpression gt;
    @XmlElement(name = "Le")
    protected TTwoChildrenExpression le;
    @XmlElement(name = "Lt")
    protected TTwoChildrenExpression lt;
    @XmlElement(name = "And")
    protected TTwoChildrenExpression and;
    @XmlElement(name = "Or")
    protected TTwoChildrenExpression or;
    @XmlElement(name = "Not")
    protected TOneChildExpression not;
    @XmlElement(name = "IsOf")
    protected TCastOrIsOfExpression isOf;
    @XmlElement(name = "LabeledElement")
    protected TLabeledElementExpression labeledElement;
    @XmlElement(name = "LabeledElementReference")
    protected TLabeledElementReferenceExpression labeledElementReference;
    @XmlElement(name = "Null")
    protected TNullExpression _null;
    @XmlElement(name = "NavigationPropertyPath")
    protected TPathExpression navigationPropertyPathElement;
    @XmlElement(name = "Path")
    protected TPathExpression pathElement;
    @XmlElement(name = "PropertyPath")
    protected TPathExpression propertyPathElement;
    @XmlElement(name = "Record")
    protected TRecordExpression record;
    @XmlElement(name = "UrlRef")
    protected TOneChildExpression urlRefElement;
    @XmlAttribute(name = "Term", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String term;
    @XmlAttribute(name = "Qualifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String qualifier;
    @XmlAttribute(name = "Binary")
    protected String binary;
    @XmlAttribute(name = "Bool")
    protected Boolean bool;
    @XmlAttribute(name = "Date")
    protected XMLGregorianCalendar date;
    @XmlAttribute(name = "DateTimeOffset")
    protected XMLGregorianCalendar dateTimeOffset;
    @XmlAttribute(name = "Decimal")
    protected BigDecimal decimal;
    @XmlAttribute(name = "Duration")
    protected Duration duration;
    @XmlAttribute(name = "EnumMember")
    protected List<String> enumMember;
    @XmlAttribute(name = "Float")
    protected Double _float;
    @XmlAttribute(name = "Guid")
    protected String guid;
    @XmlAttribute(name = "Int")
    protected BigInteger _int;
    @XmlAttribute(name = "String")
    protected String string;
    @XmlAttribute(name = "TimeOfDay")
    protected XMLGregorianCalendar timeOfDay;
    @XmlAttribute(name = "AnnotationPath")
    protected String annotationPath;
    @XmlAttribute(name = "NavigationPropertyPath")
    protected String navigationPropertyPath;
    @XmlAttribute(name = "Path")
    protected String path;
    @XmlAttribute(name = "PropertyPath")
    protected String propertyPath;
    @XmlAttribute(name = "UrlRef")
    @XmlSchemaType(name = "anyURI")
    protected String urlRef;

    /**
     * Gets the value of the annotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Annotation }
     * 
     * 
     */
    public List<Annotation> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<Annotation>();
        }
        return this.annotation;
    }

    /**
     * Gets the value of the binaryElement property.
     * 
     * @return
     *     possible object is
     *     {@link TBinaryConstantExpression }
     *     
     */
    public TBinaryConstantExpression getBinaryElement() {
        return binaryElement;
    }

    /**
     * Sets the value of the binaryElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBinaryConstantExpression }
     *     
     */
    public void setBinaryElement(TBinaryConstantExpression value) {
        this.binaryElement = value;
    }

    /**
     * Gets the value of the boolElement property.
     * 
     * @return
     *     possible object is
     *     {@link TBoolConstantExpression }
     *     
     */
    public TBoolConstantExpression getBoolElement() {
        return boolElement;
    }

    /**
     * Sets the value of the boolElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBoolConstantExpression }
     *     
     */
    public void setBoolElement(TBoolConstantExpression value) {
        this.boolElement = value;
    }

    /**
     * Gets the value of the dateElement property.
     * 
     * @return
     *     possible object is
     *     {@link TDateConstantExpression }
     *     
     */
    public TDateConstantExpression getDateElement() {
        return dateElement;
    }

    /**
     * Sets the value of the dateElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDateConstantExpression }
     *     
     */
    public void setDateElement(TDateConstantExpression value) {
        this.dateElement = value;
    }

    /**
     * Gets the value of the dateTimeOffsetElement property.
     * 
     * @return
     *     possible object is
     *     {@link TDateTimeOffsetConstantExpression }
     *     
     */
    public TDateTimeOffsetConstantExpression getDateTimeOffsetElement() {
        return dateTimeOffsetElement;
    }

    /**
     * Sets the value of the dateTimeOffsetElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDateTimeOffsetConstantExpression }
     *     
     */
    public void setDateTimeOffsetElement(TDateTimeOffsetConstantExpression value) {
        this.dateTimeOffsetElement = value;
    }

    /**
     * Gets the value of the decimalElement property.
     * 
     * @return
     *     possible object is
     *     {@link TDecimalConstantExpression }
     *     
     */
    public TDecimalConstantExpression getDecimalElement() {
        return decimalElement;
    }

    /**
     * Sets the value of the decimalElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDecimalConstantExpression }
     *     
     */
    public void setDecimalElement(TDecimalConstantExpression value) {
        this.decimalElement = value;
    }

    /**
     * Gets the value of the durationElement property.
     * 
     * @return
     *     possible object is
     *     {@link TDurationConstantExpression }
     *     
     */
    public TDurationConstantExpression getDurationElement() {
        return durationElement;
    }

    /**
     * Sets the value of the durationElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDurationConstantExpression }
     *     
     */
    public void setDurationElement(TDurationConstantExpression value) {
        this.durationElement = value;
    }

    /**
     * Gets the value of the enumMemberElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumMemberElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnumMemberElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEnumMemberElement() {
        if (enumMemberElement == null) {
            enumMemberElement = new ArrayList<String>();
        }
        return this.enumMemberElement;
    }

    /**
     * Gets the value of the floatElement property.
     * 
     * @return
     *     possible object is
     *     {@link TFloatConstantExpression }
     *     
     */
    public TFloatConstantExpression getFloatElement() {
        return floatElement;
    }

    /**
     * Sets the value of the floatElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFloatConstantExpression }
     *     
     */
    public void setFloatElement(TFloatConstantExpression value) {
        this.floatElement = value;
    }

    /**
     * Gets the value of the guidElement property.
     * 
     * @return
     *     possible object is
     *     {@link TGuidConstantExpression }
     *     
     */
    public TGuidConstantExpression getGuidElement() {
        return guidElement;
    }

    /**
     * Sets the value of the guidElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGuidConstantExpression }
     *     
     */
    public void setGuidElement(TGuidConstantExpression value) {
        this.guidElement = value;
    }

    /**
     * Gets the value of the intElement property.
     * 
     * @return
     *     possible object is
     *     {@link TIntConstantExpression }
     *     
     */
    public TIntConstantExpression getIntElement() {
        return intElement;
    }

    /**
     * Sets the value of the intElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIntConstantExpression }
     *     
     */
    public void setIntElement(TIntConstantExpression value) {
        this.intElement = value;
    }

    /**
     * Gets the value of the stringElement property.
     * 
     * @return
     *     possible object is
     *     {@link TStringConstantExpression }
     *     
     */
    public TStringConstantExpression getStringElement() {
        return stringElement;
    }

    /**
     * Sets the value of the stringElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStringConstantExpression }
     *     
     */
    public void setStringElement(TStringConstantExpression value) {
        this.stringElement = value;
    }

    /**
     * Gets the value of the timeOfDayElement property.
     * 
     * @return
     *     possible object is
     *     {@link TTimeOfDayConstantExpression }
     *     
     */
    public TTimeOfDayConstantExpression getTimeOfDayElement() {
        return timeOfDayElement;
    }

    /**
     * Sets the value of the timeOfDayElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTimeOfDayConstantExpression }
     *     
     */
    public void setTimeOfDayElement(TTimeOfDayConstantExpression value) {
        this.timeOfDayElement = value;
    }

    /**
     * Gets the value of the annotationPathElement property.
     * 
     * @return
     *     possible object is
     *     {@link TPathExpression }
     *     
     */
    public TPathExpression getAnnotationPathElement() {
        return annotationPathElement;
    }

    /**
     * Sets the value of the annotationPathElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPathExpression }
     *     
     */
    public void setAnnotationPathElement(TPathExpression value) {
        this.annotationPathElement = value;
    }

    /**
     * Gets the value of the apply property.
     * 
     * @return
     *     possible object is
     *     {@link TApplyExpression }
     *     
     */
    public TApplyExpression getApply() {
        return apply;
    }

    /**
     * Sets the value of the apply property.
     * 
     * @param value
     *     allowed object is
     *     {@link TApplyExpression }
     *     
     */
    public void setApply(TApplyExpression value) {
        this.apply = value;
    }

    /**
     * Gets the value of the cast property.
     * 
     * @return
     *     possible object is
     *     {@link TCastOrIsOfExpression }
     *     
     */
    public TCastOrIsOfExpression getCast() {
        return cast;
    }

    /**
     * Sets the value of the cast property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCastOrIsOfExpression }
     *     
     */
    public void setCast(TCastOrIsOfExpression value) {
        this.cast = value;
    }

    /**
     * Gets the value of the collection property.
     * 
     * @return
     *     possible object is
     *     {@link TCollectionExpression }
     *     
     */
    public TCollectionExpression getCollection() {
        return collection;
    }

    /**
     * Sets the value of the collection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCollectionExpression }
     *     
     */
    public void setCollection(TCollectionExpression value) {
        this.collection = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link TIfExpression }
     *     
     */
    public TIfExpression getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIfExpression }
     *     
     */
    public void setIf(TIfExpression value) {
        this._if = value;
    }

    /**
     * Gets the value of the eq property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getEq() {
        return eq;
    }

    /**
     * Sets the value of the eq property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setEq(TTwoChildrenExpression value) {
        this.eq = value;
    }

    /**
     * Gets the value of the ne property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getNe() {
        return ne;
    }

    /**
     * Sets the value of the ne property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setNe(TTwoChildrenExpression value) {
        this.ne = value;
    }

    /**
     * Gets the value of the ge property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getGe() {
        return ge;
    }

    /**
     * Sets the value of the ge property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setGe(TTwoChildrenExpression value) {
        this.ge = value;
    }

    /**
     * Gets the value of the gt property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getGt() {
        return gt;
    }

    /**
     * Sets the value of the gt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setGt(TTwoChildrenExpression value) {
        this.gt = value;
    }

    /**
     * Gets the value of the le property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getLe() {
        return le;
    }

    /**
     * Sets the value of the le property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setLe(TTwoChildrenExpression value) {
        this.le = value;
    }

    /**
     * Gets the value of the lt property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getLt() {
        return lt;
    }

    /**
     * Sets the value of the lt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setLt(TTwoChildrenExpression value) {
        this.lt = value;
    }

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setAnd(TTwoChildrenExpression value) {
        this.and = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setOr(TTwoChildrenExpression value) {
        this.or = value;
    }

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link TOneChildExpression }
     *     
     */
    public TOneChildExpression getNot() {
        return not;
    }

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOneChildExpression }
     *     
     */
    public void setNot(TOneChildExpression value) {
        this.not = value;
    }

    /**
     * Gets the value of the isOf property.
     * 
     * @return
     *     possible object is
     *     {@link TCastOrIsOfExpression }
     *     
     */
    public TCastOrIsOfExpression getIsOf() {
        return isOf;
    }

    /**
     * Sets the value of the isOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCastOrIsOfExpression }
     *     
     */
    public void setIsOf(TCastOrIsOfExpression value) {
        this.isOf = value;
    }

    /**
     * Gets the value of the labeledElement property.
     * 
     * @return
     *     possible object is
     *     {@link TLabeledElementExpression }
     *     
     */
    public TLabeledElementExpression getLabeledElement() {
        return labeledElement;
    }

    /**
     * Sets the value of the labeledElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLabeledElementExpression }
     *     
     */
    public void setLabeledElement(TLabeledElementExpression value) {
        this.labeledElement = value;
    }

    /**
     * Gets the value of the labeledElementReference property.
     * 
     * @return
     *     possible object is
     *     {@link TLabeledElementReferenceExpression }
     *     
     */
    public TLabeledElementReferenceExpression getLabeledElementReference() {
        return labeledElementReference;
    }

    /**
     * Sets the value of the labeledElementReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLabeledElementReferenceExpression }
     *     
     */
    public void setLabeledElementReference(TLabeledElementReferenceExpression value) {
        this.labeledElementReference = value;
    }

    /**
     * Gets the value of the null property.
     * 
     * @return
     *     possible object is
     *     {@link TNullExpression }
     *     
     */
    public TNullExpression getNull() {
        return _null;
    }

    /**
     * Sets the value of the null property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNullExpression }
     *     
     */
    public void setNull(TNullExpression value) {
        this._null = value;
    }

    /**
     * Gets the value of the navigationPropertyPathElement property.
     * 
     * @return
     *     possible object is
     *     {@link TPathExpression }
     *     
     */
    public TPathExpression getNavigationPropertyPathElement() {
        return navigationPropertyPathElement;
    }

    /**
     * Sets the value of the navigationPropertyPathElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPathExpression }
     *     
     */
    public void setNavigationPropertyPathElement(TPathExpression value) {
        this.navigationPropertyPathElement = value;
    }

    /**
     * Gets the value of the pathElement property.
     * 
     * @return
     *     possible object is
     *     {@link TPathExpression }
     *     
     */
    public TPathExpression getPathElement() {
        return pathElement;
    }

    /**
     * Sets the value of the pathElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPathExpression }
     *     
     */
    public void setPathElement(TPathExpression value) {
        this.pathElement = value;
    }

    /**
     * Gets the value of the propertyPathElement property.
     * 
     * @return
     *     possible object is
     *     {@link TPathExpression }
     *     
     */
    public TPathExpression getPropertyPathElement() {
        return propertyPathElement;
    }

    /**
     * Sets the value of the propertyPathElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPathExpression }
     *     
     */
    public void setPropertyPathElement(TPathExpression value) {
        this.propertyPathElement = value;
    }

    /**
     * Gets the value of the record property.
     * 
     * @return
     *     possible object is
     *     {@link TRecordExpression }
     *     
     */
    public TRecordExpression getRecord() {
        return record;
    }

    /**
     * Sets the value of the record property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRecordExpression }
     *     
     */
    public void setRecord(TRecordExpression value) {
        this.record = value;
    }

    /**
     * Gets the value of the urlRefElement property.
     * 
     * @return
     *     possible object is
     *     {@link TOneChildExpression }
     *     
     */
    public TOneChildExpression getUrlRefElement() {
        return urlRefElement;
    }

    /**
     * Sets the value of the urlRefElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOneChildExpression }
     *     
     */
    public void setUrlRefElement(TOneChildExpression value) {
        this.urlRefElement = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the qualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifier() {
        return qualifier;
    }

    /**
     * Sets the value of the qualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifier(String value) {
        this.qualifier = value;
    }

    /**
     * Gets the value of the binary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinary() {
        return binary;
    }

    /**
     * Sets the value of the binary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinary(String value) {
        this.binary = value;
    }

    /**
     * Gets the value of the bool property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBool() {
        return bool;
    }

    /**
     * Sets the value of the bool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBool(Boolean value) {
        this.bool = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the dateTimeOffset property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTimeOffset() {
        return dateTimeOffset;
    }

    /**
     * Sets the value of the dateTimeOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTimeOffset(XMLGregorianCalendar value) {
        this.dateTimeOffset = value;
    }

    /**
     * Gets the value of the decimal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDecimal() {
        return decimal;
    }

    /**
     * Sets the value of the decimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDecimal(BigDecimal value) {
        this.decimal = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the enumMember property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumMember property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnumMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEnumMember() {
        if (enumMember == null) {
            enumMember = new ArrayList<String>();
        }
        return this.enumMember;
    }

    /**
     * Gets the value of the float property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFloat() {
        return _float;
    }

    /**
     * Sets the value of the float property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFloat(Double value) {
        this._float = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the int property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInt() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInt(BigInteger value) {
        this._int = value;
    }

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setString(String value) {
        this.string = value;
    }

    /**
     * Gets the value of the timeOfDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeOfDay() {
        return timeOfDay;
    }

    /**
     * Sets the value of the timeOfDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeOfDay(XMLGregorianCalendar value) {
        this.timeOfDay = value;
    }

    /**
     * Gets the value of the annotationPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotationPath() {
        return annotationPath;
    }

    /**
     * Sets the value of the annotationPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotationPath(String value) {
        this.annotationPath = value;
    }

    /**
     * Gets the value of the navigationPropertyPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavigationPropertyPath() {
        return navigationPropertyPath;
    }

    /**
     * Sets the value of the navigationPropertyPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavigationPropertyPath(String value) {
        this.navigationPropertyPath = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

    /**
     * Gets the value of the propertyPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyPath() {
        return propertyPath;
    }

    /**
     * Sets the value of the propertyPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyPath(String value) {
        this.propertyPath = value;
    }

    /**
     * Gets the value of the urlRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrlRef() {
        return urlRef;
    }

    /**
     * Sets the value of the urlRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrlRef(String value) {
        this.urlRef = value;
    }

}
