//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TTwoChildrenExpressionEq_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Eq");
    private final static QName _TTwoChildrenExpressionLabeledElement_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "LabeledElement");
    private final static QName _TTwoChildrenExpressionGt_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Gt");
    private final static QName _TTwoChildrenExpressionInt_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Int");
    private final static QName _TTwoChildrenExpressionGuid_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Guid");
    private final static QName _TTwoChildrenExpressionString_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "String");
    private final static QName _TTwoChildrenExpressionApply_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Apply");
    private final static QName _TTwoChildrenExpressionCast_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Cast");
    private final static QName _TTwoChildrenExpressionUrlRef_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "UrlRef");
    private final static QName _TTwoChildrenExpressionNull_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Null");
    private final static QName _TTwoChildrenExpressionOr_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Or");
    private final static QName _TTwoChildrenExpressionLe_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Le");
    private final static QName _TTwoChildrenExpressionRecord_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Record");
    private final static QName _TTwoChildrenExpressionDecimal_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Decimal");
    private final static QName _TTwoChildrenExpressionBool_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Bool");
    private final static QName _TTwoChildrenExpressionNe_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Ne");
    private final static QName _TTwoChildrenExpressionEnumMember_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "EnumMember");
    private final static QName _TTwoChildrenExpressionDate_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Date");
    private final static QName _TTwoChildrenExpressionLt_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Lt");
    private final static QName _TTwoChildrenExpressionDateTimeOffset_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "DateTimeOffset");
    private final static QName _TTwoChildrenExpressionDuration_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Duration");
    private final static QName _TTwoChildrenExpressionNavigationPropertyPath_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "NavigationPropertyPath");
    private final static QName _TTwoChildrenExpressionPath_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Path");
    private final static QName _TTwoChildrenExpressionTimeOfDay_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "TimeOfDay");
    private final static QName _TTwoChildrenExpressionIsOf_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "IsOf");
    private final static QName _TTwoChildrenExpressionIf_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "If");
    private final static QName _TTwoChildrenExpressionGe_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Ge");
    private final static QName _TTwoChildrenExpressionPropertyPath_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "PropertyPath");
    private final static QName _TTwoChildrenExpressionCollection_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Collection");
    private final static QName _TTwoChildrenExpressionBinary_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Binary");
    private final static QName _TTwoChildrenExpressionAnd_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "And");
    private final static QName _TTwoChildrenExpressionLabeledElementReference_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "LabeledElementReference");
    private final static QName _TTwoChildrenExpressionFloat_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Float");
    private final static QName _TTwoChildrenExpressionAnnotationPath_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "AnnotationPath");
    private final static QName _TTwoChildrenExpressionNot_QNAME = new QName("http://docs.oasis-open.org/odata/ns/edm", "Not");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm
     * 
     */
    public ObjectFactory() {
    }


    //-------------
    //static object generators for elements of "http://docs.oasis-open.org/odata/ns/edmx" namespace

    public static Edmx createEdmx(){ return new Edmx();}

    public static DataServices createDataServices(){return new DataServices();}


    //-------------

    /**
     * Create an instance of {@link Schema }
     * 
     */
    public Schema createSchema() {
        return new Schema();
    }

    /**
     * Create an instance of {@link TComplexType }
     * 
     */
    public TComplexType createTComplexType() {
        return new TComplexType();
    }

    /**
     * Create an instance of {@link TEntityType }
     * 
     */
    public TEntityType createTEntityType() {
        return new TEntityType();
    }

    /**
     * Create an instance of {@link TTypeDefinition }
     * 
     */
    public TTypeDefinition createTTypeDefinition() {
        return new TTypeDefinition();
    }

    /**
     * Create an instance of {@link TEnumType }
     * 
     */
    public TEnumType createTEnumType() {
        return new TEnumType();
    }

    /**
     * Create an instance of {@link TAction }
     * 
     */
    public TAction createTAction() {
        return new TAction();
    }

    /**
     * Create an instance of {@link TFunction }
     * 
     */
    public TFunction createTFunction() {
        return new TFunction();
    }

    /**
     * Create an instance of {@link TTerm }
     * 
     */
    public TTerm createTTerm() {
        return new TTerm();
    }

    /**
     * Create an instance of {@link TAnnotations }
     * 
     */
    public TAnnotations createTAnnotations() {
        return new TAnnotations();
    }

    /**
     * Create an instance of {@link TEntityContainer }
     * 
     */
    public TEntityContainer createTEntityContainer() {
        return new TEntityContainer();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link TBinaryConstantExpression }
     * 
     */
    public TBinaryConstantExpression createTBinaryConstantExpression() {
        return new TBinaryConstantExpression();
    }

    /**
     * Create an instance of {@link TBoolConstantExpression }
     * 
     */
    public TBoolConstantExpression createTBoolConstantExpression() {
        return new TBoolConstantExpression();
    }

    /**
     * Create an instance of {@link TDateConstantExpression }
     * 
     */
    public TDateConstantExpression createTDateConstantExpression() {
        return new TDateConstantExpression();
    }

    /**
     * Create an instance of {@link TDateTimeOffsetConstantExpression }
     * 
     */
    public TDateTimeOffsetConstantExpression createTDateTimeOffsetConstantExpression() {
        return new TDateTimeOffsetConstantExpression();
    }

    /**
     * Create an instance of {@link TDecimalConstantExpression }
     * 
     */
    public TDecimalConstantExpression createTDecimalConstantExpression() {
        return new TDecimalConstantExpression();
    }

    /**
     * Create an instance of {@link TDurationConstantExpression }
     * 
     */
    public TDurationConstantExpression createTDurationConstantExpression() {
        return new TDurationConstantExpression();
    }

    /**
     * Create an instance of {@link TFloatConstantExpression }
     * 
     */
    public TFloatConstantExpression createTFloatConstantExpression() {
        return new TFloatConstantExpression();
    }

    /**
     * Create an instance of {@link TGuidConstantExpression }
     * 
     */
    public TGuidConstantExpression createTGuidConstantExpression() {
        return new TGuidConstantExpression();
    }

    /**
     * Create an instance of {@link TIntConstantExpression }
     * 
     */
    public TIntConstantExpression createTIntConstantExpression() {
        return new TIntConstantExpression();
    }

    /**
     * Create an instance of {@link TStringConstantExpression }
     * 
     */
    public TStringConstantExpression createTStringConstantExpression() {
        return new TStringConstantExpression();
    }

    /**
     * Create an instance of {@link TTimeOfDayConstantExpression }
     * 
     */
    public TTimeOfDayConstantExpression createTTimeOfDayConstantExpression() {
        return new TTimeOfDayConstantExpression();
    }

    /**
     * Create an instance of {@link TPathExpression }
     * 
     */
    public TPathExpression createTPathExpression() {
        return new TPathExpression();
    }

    /**
     * Create an instance of {@link TApplyExpression }
     * 
     */
    public TApplyExpression createTApplyExpression() {
        return new TApplyExpression();
    }

    /**
     * Create an instance of {@link TCastOrIsOfExpression }
     * 
     */
    public TCastOrIsOfExpression createTCastOrIsOfExpression() {
        return new TCastOrIsOfExpression();
    }

    /**
     * Create an instance of {@link TCollectionExpression }
     * 
     */
    public TCollectionExpression createTCollectionExpression() {
        return new TCollectionExpression();
    }

    /**
     * Create an instance of {@link TIfExpression }
     * 
     */
    public TIfExpression createTIfExpression() {
        return new TIfExpression();
    }

    /**
     * Create an instance of {@link TTwoChildrenExpression }
     * 
     */
    public TTwoChildrenExpression createTTwoChildrenExpression() {
        return new TTwoChildrenExpression();
    }

    /**
     * Create an instance of {@link TOneChildExpression }
     * 
     */
    public TOneChildExpression createTOneChildExpression() {
        return new TOneChildExpression();
    }

    /**
     * Create an instance of {@link TLabeledElementExpression }
     * 
     */
    public TLabeledElementExpression createTLabeledElementExpression() {
        return new TLabeledElementExpression();
    }

    /**
     * Create an instance of {@link TLabeledElementReferenceExpression }
     * 
     */
    public TLabeledElementReferenceExpression createTLabeledElementReferenceExpression() {
        return new TLabeledElementReferenceExpression();
    }

    /**
     * Create an instance of {@link TNullExpression }
     * 
     */
    public TNullExpression createTNullExpression() {
        return new TNullExpression();
    }

    /**
     * Create an instance of {@link TRecordExpression }
     * 
     */
    public TRecordExpression createTRecordExpression() {
        return new TRecordExpression();
    }

    /**
     * Create an instance of {@link TActionFunctionParameter }
     * 
     */
    public TActionFunctionParameter createTActionFunctionParameter() {
        return new TActionFunctionParameter();
    }

    /**
     * Create an instance of {@link TActionFunctionReturnType }
     * 
     */
    public TActionFunctionReturnType createTActionFunctionReturnType() {
        return new TActionFunctionReturnType();
    }

    /**
     * Create an instance of {@link TPropertyRef }
     * 
     */
    public TPropertyRef createTPropertyRef() {
        return new TPropertyRef();
    }

    /**
     * Create an instance of {@link TPropertyValue }
     * 
     */
    public TPropertyValue createTPropertyValue() {
        return new TPropertyValue();
    }

    /**
     * Create an instance of {@link TProperty }
     * 
     */
    public TProperty createTProperty() {
        return new TProperty();
    }

    /**
     * Create an instance of {@link TActionImport }
     * 
     */
    public TActionImport createTActionImport() {
        return new TActionImport();
    }

    /**
     * Create an instance of {@link TNavigationPropertyBinding }
     * 
     */
    public TNavigationPropertyBinding createTNavigationPropertyBinding() {
        return new TNavigationPropertyBinding();
    }

    /**
     * Create an instance of {@link TEnumTypeMember }
     * 
     */
    public TEnumTypeMember createTEnumTypeMember() {
        return new TEnumTypeMember();
    }

    /**
     * Create an instance of {@link TSingleton }
     * 
     */
    public TSingleton createTSingleton() {
        return new TSingleton();
    }

    /**
     * Create an instance of {@link TEntityKeyElement }
     * 
     */
    public TEntityKeyElement createTEntityKeyElement() {
        return new TEntityKeyElement();
    }

    /**
     * Create an instance of {@link TFunctionImport }
     * 
     */
    public TFunctionImport createTFunctionImport() {
        return new TFunctionImport();
    }

    /**
     * Create an instance of {@link TEntitySet }
     * 
     */
    public TEntitySet createTEntitySet() {
        return new TEntitySet();
    }

    /**
     * Create an instance of {@link TOnDelete }
     * 
     */
    public TOnDelete createTOnDelete() {
        return new TOnDelete();
    }

    /**
     * Create an instance of {@link TNavigationProperty }
     * 
     */
    public TNavigationProperty createTNavigationProperty() {
        return new TNavigationProperty();
    }

    /**
     * Create an instance of {@link TReferentialConstraint }
     * 
     */
    public TReferentialConstraint createTReferentialConstraint() {
        return new TReferentialConstraint();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Eq", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTTwoChildrenExpressionEq(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionEq_QNAME, TTwoChildrenExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLabeledElementExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "LabeledElement", scope = TTwoChildrenExpression.class)
    public JAXBElement<TLabeledElementExpression> createTTwoChildrenExpressionLabeledElement(TLabeledElementExpression value) {
        return new JAXBElement<TLabeledElementExpression>(_TTwoChildrenExpressionLabeledElement_QNAME, TLabeledElementExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Gt", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTTwoChildrenExpressionGt(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionGt_QNAME, TTwoChildrenExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIntConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Int", scope = TTwoChildrenExpression.class)
    public JAXBElement<TIntConstantExpression> createTTwoChildrenExpressionInt(TIntConstantExpression value) {
        return new JAXBElement<TIntConstantExpression>(_TTwoChildrenExpressionInt_QNAME, TIntConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGuidConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Guid", scope = TTwoChildrenExpression.class)
    public JAXBElement<TGuidConstantExpression> createTTwoChildrenExpressionGuid(TGuidConstantExpression value) {
        return new JAXBElement<TGuidConstantExpression>(_TTwoChildrenExpressionGuid_QNAME, TGuidConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStringConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "String", scope = TTwoChildrenExpression.class)
    public JAXBElement<TStringConstantExpression> createTTwoChildrenExpressionString(TStringConstantExpression value) {
        return new JAXBElement<TStringConstantExpression>(_TTwoChildrenExpressionString_QNAME, TStringConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TApplyExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Apply", scope = TTwoChildrenExpression.class)
    public JAXBElement<TApplyExpression> createTTwoChildrenExpressionApply(TApplyExpression value) {
        return new JAXBElement<TApplyExpression>(_TTwoChildrenExpressionApply_QNAME, TApplyExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Cast", scope = TTwoChildrenExpression.class)
    public JAXBElement<TCastOrIsOfExpression> createTTwoChildrenExpressionCast(TCastOrIsOfExpression value) {
        return new JAXBElement<TCastOrIsOfExpression>(_TTwoChildrenExpressionCast_QNAME, TCastOrIsOfExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "UrlRef", scope = TTwoChildrenExpression.class)
    public JAXBElement<TOneChildExpression> createTTwoChildrenExpressionUrlRef(TOneChildExpression value) {
        return new JAXBElement<TOneChildExpression>(_TTwoChildrenExpressionUrlRef_QNAME, TOneChildExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNullExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Null", scope = TTwoChildrenExpression.class)
    public JAXBElement<TNullExpression> createTTwoChildrenExpressionNull(TNullExpression value) {
        return new JAXBElement<TNullExpression>(_TTwoChildrenExpressionNull_QNAME, TNullExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Or", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTTwoChildrenExpressionOr(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionOr_QNAME, TTwoChildrenExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Le", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTTwoChildrenExpressionLe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionLe_QNAME, TTwoChildrenExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRecordExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Record", scope = TTwoChildrenExpression.class)
    public JAXBElement<TRecordExpression> createTTwoChildrenExpressionRecord(TRecordExpression value) {
        return new JAXBElement<TRecordExpression>(_TTwoChildrenExpressionRecord_QNAME, TRecordExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecimalConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Decimal", scope = TTwoChildrenExpression.class)
    public JAXBElement<TDecimalConstantExpression> createTTwoChildrenExpressionDecimal(TDecimalConstantExpression value) {
        return new JAXBElement<TDecimalConstantExpression>(_TTwoChildrenExpressionDecimal_QNAME, TDecimalConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBoolConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Bool", scope = TTwoChildrenExpression.class)
    public JAXBElement<TBoolConstantExpression> createTTwoChildrenExpressionBool(TBoolConstantExpression value) {
        return new JAXBElement<TBoolConstantExpression>(_TTwoChildrenExpressionBool_QNAME, TBoolConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Ne", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTTwoChildrenExpressionNe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionNe_QNAME, TTwoChildrenExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "EnumMember", scope = TTwoChildrenExpression.class)
    public JAXBElement<List<String>> createTTwoChildrenExpressionEnumMember(List<String> value) {
        return new JAXBElement<List<String>>(_TTwoChildrenExpressionEnumMember_QNAME, ((Class) List.class), TTwoChildrenExpression.class, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDateConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Date", scope = TTwoChildrenExpression.class)
    public JAXBElement<TDateConstantExpression> createTTwoChildrenExpressionDate(TDateConstantExpression value) {
        return new JAXBElement<TDateConstantExpression>(_TTwoChildrenExpressionDate_QNAME, TDateConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Lt", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTTwoChildrenExpressionLt(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionLt_QNAME, TTwoChildrenExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDateTimeOffsetConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "DateTimeOffset", scope = TTwoChildrenExpression.class)
    public JAXBElement<TDateTimeOffsetConstantExpression> createTTwoChildrenExpressionDateTimeOffset(TDateTimeOffsetConstantExpression value) {
        return new JAXBElement<TDateTimeOffsetConstantExpression>(_TTwoChildrenExpressionDateTimeOffset_QNAME, TDateTimeOffsetConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDurationConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Duration", scope = TTwoChildrenExpression.class)
    public JAXBElement<TDurationConstantExpression> createTTwoChildrenExpressionDuration(TDurationConstantExpression value) {
        return new JAXBElement<TDurationConstantExpression>(_TTwoChildrenExpressionDuration_QNAME, TDurationConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "NavigationPropertyPath", scope = TTwoChildrenExpression.class)
    public JAXBElement<TPathExpression> createTTwoChildrenExpressionNavigationPropertyPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionNavigationPropertyPath_QNAME, TPathExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Path", scope = TTwoChildrenExpression.class)
    public JAXBElement<TPathExpression> createTTwoChildrenExpressionPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionPath_QNAME, TPathExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTimeOfDayConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "TimeOfDay", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTimeOfDayConstantExpression> createTTwoChildrenExpressionTimeOfDay(TTimeOfDayConstantExpression value) {
        return new JAXBElement<TTimeOfDayConstantExpression>(_TTwoChildrenExpressionTimeOfDay_QNAME, TTimeOfDayConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "IsOf", scope = TTwoChildrenExpression.class)
    public JAXBElement<TCastOrIsOfExpression> createTTwoChildrenExpressionIsOf(TCastOrIsOfExpression value) {
        return new JAXBElement<TCastOrIsOfExpression>(_TTwoChildrenExpressionIsOf_QNAME, TCastOrIsOfExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "If", scope = TTwoChildrenExpression.class)
    public JAXBElement<TIfExpression> createTTwoChildrenExpressionIf(TIfExpression value) {
        return new JAXBElement<TIfExpression>(_TTwoChildrenExpressionIf_QNAME, TIfExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Ge", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTTwoChildrenExpressionGe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionGe_QNAME, TTwoChildrenExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "PropertyPath", scope = TTwoChildrenExpression.class)
    public JAXBElement<TPathExpression> createTTwoChildrenExpressionPropertyPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionPropertyPath_QNAME, TPathExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCollectionExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Collection", scope = TTwoChildrenExpression.class)
    public JAXBElement<TCollectionExpression> createTTwoChildrenExpressionCollection(TCollectionExpression value) {
        return new JAXBElement<TCollectionExpression>(_TTwoChildrenExpressionCollection_QNAME, TCollectionExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBinaryConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Binary", scope = TTwoChildrenExpression.class)
    public JAXBElement<TBinaryConstantExpression> createTTwoChildrenExpressionBinary(TBinaryConstantExpression value) {
        return new JAXBElement<TBinaryConstantExpression>(_TTwoChildrenExpressionBinary_QNAME, TBinaryConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "And", scope = TTwoChildrenExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTTwoChildrenExpressionAnd(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionAnd_QNAME, TTwoChildrenExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLabeledElementReferenceExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "LabeledElementReference", scope = TTwoChildrenExpression.class)
    public JAXBElement<TLabeledElementReferenceExpression> createTTwoChildrenExpressionLabeledElementReference(TLabeledElementReferenceExpression value) {
        return new JAXBElement<TLabeledElementReferenceExpression>(_TTwoChildrenExpressionLabeledElementReference_QNAME, TLabeledElementReferenceExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFloatConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Float", scope = TTwoChildrenExpression.class)
    public JAXBElement<TFloatConstantExpression> createTTwoChildrenExpressionFloat(TFloatConstantExpression value) {
        return new JAXBElement<TFloatConstantExpression>(_TTwoChildrenExpressionFloat_QNAME, TFloatConstantExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "AnnotationPath", scope = TTwoChildrenExpression.class)
    public JAXBElement<TPathExpression> createTTwoChildrenExpressionAnnotationPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionAnnotationPath_QNAME, TPathExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Not", scope = TTwoChildrenExpression.class)
    public JAXBElement<TOneChildExpression> createTTwoChildrenExpressionNot(TOneChildExpression value) {
        return new JAXBElement<TOneChildExpression>(_TTwoChildrenExpressionNot_QNAME, TOneChildExpression.class, TTwoChildrenExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Eq", scope = TApplyExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTApplyExpressionEq(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionEq_QNAME, TTwoChildrenExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLabeledElementExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "LabeledElement", scope = TApplyExpression.class)
    public JAXBElement<TLabeledElementExpression> createTApplyExpressionLabeledElement(TLabeledElementExpression value) {
        return new JAXBElement<TLabeledElementExpression>(_TTwoChildrenExpressionLabeledElement_QNAME, TLabeledElementExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Gt", scope = TApplyExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTApplyExpressionGt(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionGt_QNAME, TTwoChildrenExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIntConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Int", scope = TApplyExpression.class)
    public JAXBElement<TIntConstantExpression> createTApplyExpressionInt(TIntConstantExpression value) {
        return new JAXBElement<TIntConstantExpression>(_TTwoChildrenExpressionInt_QNAME, TIntConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGuidConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Guid", scope = TApplyExpression.class)
    public JAXBElement<TGuidConstantExpression> createTApplyExpressionGuid(TGuidConstantExpression value) {
        return new JAXBElement<TGuidConstantExpression>(_TTwoChildrenExpressionGuid_QNAME, TGuidConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStringConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "String", scope = TApplyExpression.class)
    public JAXBElement<TStringConstantExpression> createTApplyExpressionString(TStringConstantExpression value) {
        return new JAXBElement<TStringConstantExpression>(_TTwoChildrenExpressionString_QNAME, TStringConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TApplyExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Apply", scope = TApplyExpression.class)
    public JAXBElement<TApplyExpression> createTApplyExpressionApply(TApplyExpression value) {
        return new JAXBElement<TApplyExpression>(_TTwoChildrenExpressionApply_QNAME, TApplyExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Cast", scope = TApplyExpression.class)
    public JAXBElement<TCastOrIsOfExpression> createTApplyExpressionCast(TCastOrIsOfExpression value) {
        return new JAXBElement<TCastOrIsOfExpression>(_TTwoChildrenExpressionCast_QNAME, TCastOrIsOfExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "UrlRef", scope = TApplyExpression.class)
    public JAXBElement<TOneChildExpression> createTApplyExpressionUrlRef(TOneChildExpression value) {
        return new JAXBElement<TOneChildExpression>(_TTwoChildrenExpressionUrlRef_QNAME, TOneChildExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNullExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Null", scope = TApplyExpression.class)
    public JAXBElement<TNullExpression> createTApplyExpressionNull(TNullExpression value) {
        return new JAXBElement<TNullExpression>(_TTwoChildrenExpressionNull_QNAME, TNullExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Or", scope = TApplyExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTApplyExpressionOr(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionOr_QNAME, TTwoChildrenExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Le", scope = TApplyExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTApplyExpressionLe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionLe_QNAME, TTwoChildrenExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRecordExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Record", scope = TApplyExpression.class)
    public JAXBElement<TRecordExpression> createTApplyExpressionRecord(TRecordExpression value) {
        return new JAXBElement<TRecordExpression>(_TTwoChildrenExpressionRecord_QNAME, TRecordExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecimalConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Decimal", scope = TApplyExpression.class)
    public JAXBElement<TDecimalConstantExpression> createTApplyExpressionDecimal(TDecimalConstantExpression value) {
        return new JAXBElement<TDecimalConstantExpression>(_TTwoChildrenExpressionDecimal_QNAME, TDecimalConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBoolConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Bool", scope = TApplyExpression.class)
    public JAXBElement<TBoolConstantExpression> createTApplyExpressionBool(TBoolConstantExpression value) {
        return new JAXBElement<TBoolConstantExpression>(_TTwoChildrenExpressionBool_QNAME, TBoolConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Ne", scope = TApplyExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTApplyExpressionNe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionNe_QNAME, TTwoChildrenExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "EnumMember", scope = TApplyExpression.class)
    public JAXBElement<List<String>> createTApplyExpressionEnumMember(List<String> value) {
        return new JAXBElement<List<String>>(_TTwoChildrenExpressionEnumMember_QNAME, ((Class) List.class), TApplyExpression.class, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDateConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Date", scope = TApplyExpression.class)
    public JAXBElement<TDateConstantExpression> createTApplyExpressionDate(TDateConstantExpression value) {
        return new JAXBElement<TDateConstantExpression>(_TTwoChildrenExpressionDate_QNAME, TDateConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Lt", scope = TApplyExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTApplyExpressionLt(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionLt_QNAME, TTwoChildrenExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDateTimeOffsetConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "DateTimeOffset", scope = TApplyExpression.class)
    public JAXBElement<TDateTimeOffsetConstantExpression> createTApplyExpressionDateTimeOffset(TDateTimeOffsetConstantExpression value) {
        return new JAXBElement<TDateTimeOffsetConstantExpression>(_TTwoChildrenExpressionDateTimeOffset_QNAME, TDateTimeOffsetConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDurationConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Duration", scope = TApplyExpression.class)
    public JAXBElement<TDurationConstantExpression> createTApplyExpressionDuration(TDurationConstantExpression value) {
        return new JAXBElement<TDurationConstantExpression>(_TTwoChildrenExpressionDuration_QNAME, TDurationConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "NavigationPropertyPath", scope = TApplyExpression.class)
    public JAXBElement<TPathExpression> createTApplyExpressionNavigationPropertyPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionNavigationPropertyPath_QNAME, TPathExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Path", scope = TApplyExpression.class)
    public JAXBElement<TPathExpression> createTApplyExpressionPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionPath_QNAME, TPathExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTimeOfDayConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "TimeOfDay", scope = TApplyExpression.class)
    public JAXBElement<TTimeOfDayConstantExpression> createTApplyExpressionTimeOfDay(TTimeOfDayConstantExpression value) {
        return new JAXBElement<TTimeOfDayConstantExpression>(_TTwoChildrenExpressionTimeOfDay_QNAME, TTimeOfDayConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "IsOf", scope = TApplyExpression.class)
    public JAXBElement<TCastOrIsOfExpression> createTApplyExpressionIsOf(TCastOrIsOfExpression value) {
        return new JAXBElement<TCastOrIsOfExpression>(_TTwoChildrenExpressionIsOf_QNAME, TCastOrIsOfExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "If", scope = TApplyExpression.class)
    public JAXBElement<TIfExpression> createTApplyExpressionIf(TIfExpression value) {
        return new JAXBElement<TIfExpression>(_TTwoChildrenExpressionIf_QNAME, TIfExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Ge", scope = TApplyExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTApplyExpressionGe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionGe_QNAME, TTwoChildrenExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "PropertyPath", scope = TApplyExpression.class)
    public JAXBElement<TPathExpression> createTApplyExpressionPropertyPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionPropertyPath_QNAME, TPathExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCollectionExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Collection", scope = TApplyExpression.class)
    public JAXBElement<TCollectionExpression> createTApplyExpressionCollection(TCollectionExpression value) {
        return new JAXBElement<TCollectionExpression>(_TTwoChildrenExpressionCollection_QNAME, TCollectionExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBinaryConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Binary", scope = TApplyExpression.class)
    public JAXBElement<TBinaryConstantExpression> createTApplyExpressionBinary(TBinaryConstantExpression value) {
        return new JAXBElement<TBinaryConstantExpression>(_TTwoChildrenExpressionBinary_QNAME, TBinaryConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "And", scope = TApplyExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTApplyExpressionAnd(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionAnd_QNAME, TTwoChildrenExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLabeledElementReferenceExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "LabeledElementReference", scope = TApplyExpression.class)
    public JAXBElement<TLabeledElementReferenceExpression> createTApplyExpressionLabeledElementReference(TLabeledElementReferenceExpression value) {
        return new JAXBElement<TLabeledElementReferenceExpression>(_TTwoChildrenExpressionLabeledElementReference_QNAME, TLabeledElementReferenceExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFloatConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Float", scope = TApplyExpression.class)
    public JAXBElement<TFloatConstantExpression> createTApplyExpressionFloat(TFloatConstantExpression value) {
        return new JAXBElement<TFloatConstantExpression>(_TTwoChildrenExpressionFloat_QNAME, TFloatConstantExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "AnnotationPath", scope = TApplyExpression.class)
    public JAXBElement<TPathExpression> createTApplyExpressionAnnotationPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionAnnotationPath_QNAME, TPathExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Not", scope = TApplyExpression.class)
    public JAXBElement<TOneChildExpression> createTApplyExpressionNot(TOneChildExpression value) {
        return new JAXBElement<TOneChildExpression>(_TTwoChildrenExpressionNot_QNAME, TOneChildExpression.class, TApplyExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Eq", scope = TCollectionExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTCollectionExpressionEq(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionEq_QNAME, TTwoChildrenExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLabeledElementExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "LabeledElement", scope = TCollectionExpression.class)
    public JAXBElement<TLabeledElementExpression> createTCollectionExpressionLabeledElement(TLabeledElementExpression value) {
        return new JAXBElement<TLabeledElementExpression>(_TTwoChildrenExpressionLabeledElement_QNAME, TLabeledElementExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Gt", scope = TCollectionExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTCollectionExpressionGt(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionGt_QNAME, TTwoChildrenExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIntConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Int", scope = TCollectionExpression.class)
    public JAXBElement<TIntConstantExpression> createTCollectionExpressionInt(TIntConstantExpression value) {
        return new JAXBElement<TIntConstantExpression>(_TTwoChildrenExpressionInt_QNAME, TIntConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGuidConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Guid", scope = TCollectionExpression.class)
    public JAXBElement<TGuidConstantExpression> createTCollectionExpressionGuid(TGuidConstantExpression value) {
        return new JAXBElement<TGuidConstantExpression>(_TTwoChildrenExpressionGuid_QNAME, TGuidConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStringConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "String", scope = TCollectionExpression.class)
    public JAXBElement<TStringConstantExpression> createTCollectionExpressionString(TStringConstantExpression value) {
        return new JAXBElement<TStringConstantExpression>(_TTwoChildrenExpressionString_QNAME, TStringConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TApplyExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Apply", scope = TCollectionExpression.class)
    public JAXBElement<TApplyExpression> createTCollectionExpressionApply(TApplyExpression value) {
        return new JAXBElement<TApplyExpression>(_TTwoChildrenExpressionApply_QNAME, TApplyExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Cast", scope = TCollectionExpression.class)
    public JAXBElement<TCastOrIsOfExpression> createTCollectionExpressionCast(TCastOrIsOfExpression value) {
        return new JAXBElement<TCastOrIsOfExpression>(_TTwoChildrenExpressionCast_QNAME, TCastOrIsOfExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "UrlRef", scope = TCollectionExpression.class)
    public JAXBElement<TOneChildExpression> createTCollectionExpressionUrlRef(TOneChildExpression value) {
        return new JAXBElement<TOneChildExpression>(_TTwoChildrenExpressionUrlRef_QNAME, TOneChildExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNullExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Null", scope = TCollectionExpression.class)
    public JAXBElement<TNullExpression> createTCollectionExpressionNull(TNullExpression value) {
        return new JAXBElement<TNullExpression>(_TTwoChildrenExpressionNull_QNAME, TNullExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Or", scope = TCollectionExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTCollectionExpressionOr(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionOr_QNAME, TTwoChildrenExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Le", scope = TCollectionExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTCollectionExpressionLe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionLe_QNAME, TTwoChildrenExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRecordExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Record", scope = TCollectionExpression.class)
    public JAXBElement<TRecordExpression> createTCollectionExpressionRecord(TRecordExpression value) {
        return new JAXBElement<TRecordExpression>(_TTwoChildrenExpressionRecord_QNAME, TRecordExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecimalConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Decimal", scope = TCollectionExpression.class)
    public JAXBElement<TDecimalConstantExpression> createTCollectionExpressionDecimal(TDecimalConstantExpression value) {
        return new JAXBElement<TDecimalConstantExpression>(_TTwoChildrenExpressionDecimal_QNAME, TDecimalConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBoolConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Bool", scope = TCollectionExpression.class)
    public JAXBElement<TBoolConstantExpression> createTCollectionExpressionBool(TBoolConstantExpression value) {
        return new JAXBElement<TBoolConstantExpression>(_TTwoChildrenExpressionBool_QNAME, TBoolConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Ne", scope = TCollectionExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTCollectionExpressionNe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionNe_QNAME, TTwoChildrenExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "EnumMember", scope = TCollectionExpression.class)
    public JAXBElement<List<String>> createTCollectionExpressionEnumMember(List<String> value) {
        return new JAXBElement<List<String>>(_TTwoChildrenExpressionEnumMember_QNAME, ((Class) List.class), TCollectionExpression.class, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDateConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Date", scope = TCollectionExpression.class)
    public JAXBElement<TDateConstantExpression> createTCollectionExpressionDate(TDateConstantExpression value) {
        return new JAXBElement<TDateConstantExpression>(_TTwoChildrenExpressionDate_QNAME, TDateConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Lt", scope = TCollectionExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTCollectionExpressionLt(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionLt_QNAME, TTwoChildrenExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDateTimeOffsetConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "DateTimeOffset", scope = TCollectionExpression.class)
    public JAXBElement<TDateTimeOffsetConstantExpression> createTCollectionExpressionDateTimeOffset(TDateTimeOffsetConstantExpression value) {
        return new JAXBElement<TDateTimeOffsetConstantExpression>(_TTwoChildrenExpressionDateTimeOffset_QNAME, TDateTimeOffsetConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDurationConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Duration", scope = TCollectionExpression.class)
    public JAXBElement<TDurationConstantExpression> createTCollectionExpressionDuration(TDurationConstantExpression value) {
        return new JAXBElement<TDurationConstantExpression>(_TTwoChildrenExpressionDuration_QNAME, TDurationConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "NavigationPropertyPath", scope = TCollectionExpression.class)
    public JAXBElement<TPathExpression> createTCollectionExpressionNavigationPropertyPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionNavigationPropertyPath_QNAME, TPathExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Path", scope = TCollectionExpression.class)
    public JAXBElement<TPathExpression> createTCollectionExpressionPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionPath_QNAME, TPathExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTimeOfDayConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "TimeOfDay", scope = TCollectionExpression.class)
    public JAXBElement<TTimeOfDayConstantExpression> createTCollectionExpressionTimeOfDay(TTimeOfDayConstantExpression value) {
        return new JAXBElement<TTimeOfDayConstantExpression>(_TTwoChildrenExpressionTimeOfDay_QNAME, TTimeOfDayConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "IsOf", scope = TCollectionExpression.class)
    public JAXBElement<TCastOrIsOfExpression> createTCollectionExpressionIsOf(TCastOrIsOfExpression value) {
        return new JAXBElement<TCastOrIsOfExpression>(_TTwoChildrenExpressionIsOf_QNAME, TCastOrIsOfExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "If", scope = TCollectionExpression.class)
    public JAXBElement<TIfExpression> createTCollectionExpressionIf(TIfExpression value) {
        return new JAXBElement<TIfExpression>(_TTwoChildrenExpressionIf_QNAME, TIfExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Ge", scope = TCollectionExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTCollectionExpressionGe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionGe_QNAME, TTwoChildrenExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "PropertyPath", scope = TCollectionExpression.class)
    public JAXBElement<TPathExpression> createTCollectionExpressionPropertyPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionPropertyPath_QNAME, TPathExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCollectionExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Collection", scope = TCollectionExpression.class)
    public JAXBElement<TCollectionExpression> createTCollectionExpressionCollection(TCollectionExpression value) {
        return new JAXBElement<TCollectionExpression>(_TTwoChildrenExpressionCollection_QNAME, TCollectionExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBinaryConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Binary", scope = TCollectionExpression.class)
    public JAXBElement<TBinaryConstantExpression> createTCollectionExpressionBinary(TBinaryConstantExpression value) {
        return new JAXBElement<TBinaryConstantExpression>(_TTwoChildrenExpressionBinary_QNAME, TBinaryConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "And", scope = TCollectionExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTCollectionExpressionAnd(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionAnd_QNAME, TTwoChildrenExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLabeledElementReferenceExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "LabeledElementReference", scope = TCollectionExpression.class)
    public JAXBElement<TLabeledElementReferenceExpression> createTCollectionExpressionLabeledElementReference(TLabeledElementReferenceExpression value) {
        return new JAXBElement<TLabeledElementReferenceExpression>(_TTwoChildrenExpressionLabeledElementReference_QNAME, TLabeledElementReferenceExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFloatConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Float", scope = TCollectionExpression.class)
    public JAXBElement<TFloatConstantExpression> createTCollectionExpressionFloat(TFloatConstantExpression value) {
        return new JAXBElement<TFloatConstantExpression>(_TTwoChildrenExpressionFloat_QNAME, TFloatConstantExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "AnnotationPath", scope = TCollectionExpression.class)
    public JAXBElement<TPathExpression> createTCollectionExpressionAnnotationPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionAnnotationPath_QNAME, TPathExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Not", scope = TCollectionExpression.class)
    public JAXBElement<TOneChildExpression> createTCollectionExpressionNot(TOneChildExpression value) {
        return new JAXBElement<TOneChildExpression>(_TTwoChildrenExpressionNot_QNAME, TOneChildExpression.class, TCollectionExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Eq", scope = TIfExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTIfExpressionEq(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionEq_QNAME, TTwoChildrenExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLabeledElementExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "LabeledElement", scope = TIfExpression.class)
    public JAXBElement<TLabeledElementExpression> createTIfExpressionLabeledElement(TLabeledElementExpression value) {
        return new JAXBElement<TLabeledElementExpression>(_TTwoChildrenExpressionLabeledElement_QNAME, TLabeledElementExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Gt", scope = TIfExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTIfExpressionGt(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionGt_QNAME, TTwoChildrenExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIntConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Int", scope = TIfExpression.class)
    public JAXBElement<TIntConstantExpression> createTIfExpressionInt(TIntConstantExpression value) {
        return new JAXBElement<TIntConstantExpression>(_TTwoChildrenExpressionInt_QNAME, TIntConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TGuidConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Guid", scope = TIfExpression.class)
    public JAXBElement<TGuidConstantExpression> createTIfExpressionGuid(TGuidConstantExpression value) {
        return new JAXBElement<TGuidConstantExpression>(_TTwoChildrenExpressionGuid_QNAME, TGuidConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TStringConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "String", scope = TIfExpression.class)
    public JAXBElement<TStringConstantExpression> createTIfExpressionString(TStringConstantExpression value) {
        return new JAXBElement<TStringConstantExpression>(_TTwoChildrenExpressionString_QNAME, TStringConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TApplyExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Apply", scope = TIfExpression.class)
    public JAXBElement<TApplyExpression> createTIfExpressionApply(TApplyExpression value) {
        return new JAXBElement<TApplyExpression>(_TTwoChildrenExpressionApply_QNAME, TApplyExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Cast", scope = TIfExpression.class)
    public JAXBElement<TCastOrIsOfExpression> createTIfExpressionCast(TCastOrIsOfExpression value) {
        return new JAXBElement<TCastOrIsOfExpression>(_TTwoChildrenExpressionCast_QNAME, TCastOrIsOfExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "UrlRef", scope = TIfExpression.class)
    public JAXBElement<TOneChildExpression> createTIfExpressionUrlRef(TOneChildExpression value) {
        return new JAXBElement<TOneChildExpression>(_TTwoChildrenExpressionUrlRef_QNAME, TOneChildExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNullExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Null", scope = TIfExpression.class)
    public JAXBElement<TNullExpression> createTIfExpressionNull(TNullExpression value) {
        return new JAXBElement<TNullExpression>(_TTwoChildrenExpressionNull_QNAME, TNullExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Or", scope = TIfExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTIfExpressionOr(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionOr_QNAME, TTwoChildrenExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Le", scope = TIfExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTIfExpressionLe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionLe_QNAME, TTwoChildrenExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRecordExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Record", scope = TIfExpression.class)
    public JAXBElement<TRecordExpression> createTIfExpressionRecord(TRecordExpression value) {
        return new JAXBElement<TRecordExpression>(_TTwoChildrenExpressionRecord_QNAME, TRecordExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDecimalConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Decimal", scope = TIfExpression.class)
    public JAXBElement<TDecimalConstantExpression> createTIfExpressionDecimal(TDecimalConstantExpression value) {
        return new JAXBElement<TDecimalConstantExpression>(_TTwoChildrenExpressionDecimal_QNAME, TDecimalConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBoolConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Bool", scope = TIfExpression.class)
    public JAXBElement<TBoolConstantExpression> createTIfExpressionBool(TBoolConstantExpression value) {
        return new JAXBElement<TBoolConstantExpression>(_TTwoChildrenExpressionBool_QNAME, TBoolConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Ne", scope = TIfExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTIfExpressionNe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionNe_QNAME, TTwoChildrenExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "EnumMember", scope = TIfExpression.class)
    public JAXBElement<List<String>> createTIfExpressionEnumMember(List<String> value) {
        return new JAXBElement<List<String>>(_TTwoChildrenExpressionEnumMember_QNAME, ((Class) List.class), TIfExpression.class, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDateConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Date", scope = TIfExpression.class)
    public JAXBElement<TDateConstantExpression> createTIfExpressionDate(TDateConstantExpression value) {
        return new JAXBElement<TDateConstantExpression>(_TTwoChildrenExpressionDate_QNAME, TDateConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Lt", scope = TIfExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTIfExpressionLt(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionLt_QNAME, TTwoChildrenExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDateTimeOffsetConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "DateTimeOffset", scope = TIfExpression.class)
    public JAXBElement<TDateTimeOffsetConstantExpression> createTIfExpressionDateTimeOffset(TDateTimeOffsetConstantExpression value) {
        return new JAXBElement<TDateTimeOffsetConstantExpression>(_TTwoChildrenExpressionDateTimeOffset_QNAME, TDateTimeOffsetConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDurationConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Duration", scope = TIfExpression.class)
    public JAXBElement<TDurationConstantExpression> createTIfExpressionDuration(TDurationConstantExpression value) {
        return new JAXBElement<TDurationConstantExpression>(_TTwoChildrenExpressionDuration_QNAME, TDurationConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "NavigationPropertyPath", scope = TIfExpression.class)
    public JAXBElement<TPathExpression> createTIfExpressionNavigationPropertyPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionNavigationPropertyPath_QNAME, TPathExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Path", scope = TIfExpression.class)
    public JAXBElement<TPathExpression> createTIfExpressionPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionPath_QNAME, TPathExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTimeOfDayConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "TimeOfDay", scope = TIfExpression.class)
    public JAXBElement<TTimeOfDayConstantExpression> createTIfExpressionTimeOfDay(TTimeOfDayConstantExpression value) {
        return new JAXBElement<TTimeOfDayConstantExpression>(_TTwoChildrenExpressionTimeOfDay_QNAME, TTimeOfDayConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "IsOf", scope = TIfExpression.class)
    public JAXBElement<TCastOrIsOfExpression> createTIfExpressionIsOf(TCastOrIsOfExpression value) {
        return new JAXBElement<TCastOrIsOfExpression>(_TTwoChildrenExpressionIsOf_QNAME, TCastOrIsOfExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TIfExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "If", scope = TIfExpression.class)
    public JAXBElement<TIfExpression> createTIfExpressionIf(TIfExpression value) {
        return new JAXBElement<TIfExpression>(_TTwoChildrenExpressionIf_QNAME, TIfExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Ge", scope = TIfExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTIfExpressionGe(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionGe_QNAME, TTwoChildrenExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "PropertyPath", scope = TIfExpression.class)
    public JAXBElement<TPathExpression> createTIfExpressionPropertyPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionPropertyPath_QNAME, TPathExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCollectionExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Collection", scope = TIfExpression.class)
    public JAXBElement<TCollectionExpression> createTIfExpressionCollection(TCollectionExpression value) {
        return new JAXBElement<TCollectionExpression>(_TTwoChildrenExpressionCollection_QNAME, TCollectionExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TBinaryConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Binary", scope = TIfExpression.class)
    public JAXBElement<TBinaryConstantExpression> createTIfExpressionBinary(TBinaryConstantExpression value) {
        return new JAXBElement<TBinaryConstantExpression>(_TTwoChildrenExpressionBinary_QNAME, TBinaryConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "And", scope = TIfExpression.class)
    public JAXBElement<TTwoChildrenExpression> createTIfExpressionAnd(TTwoChildrenExpression value) {
        return new JAXBElement<TTwoChildrenExpression>(_TTwoChildrenExpressionAnd_QNAME, TTwoChildrenExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLabeledElementReferenceExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "LabeledElementReference", scope = TIfExpression.class)
    public JAXBElement<TLabeledElementReferenceExpression> createTIfExpressionLabeledElementReference(TLabeledElementReferenceExpression value) {
        return new JAXBElement<TLabeledElementReferenceExpression>(_TTwoChildrenExpressionLabeledElementReference_QNAME, TLabeledElementReferenceExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFloatConstantExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Float", scope = TIfExpression.class)
    public JAXBElement<TFloatConstantExpression> createTIfExpressionFloat(TFloatConstantExpression value) {
        return new JAXBElement<TFloatConstantExpression>(_TTwoChildrenExpressionFloat_QNAME, TFloatConstantExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "AnnotationPath", scope = TIfExpression.class)
    public JAXBElement<TPathExpression> createTIfExpressionAnnotationPath(TPathExpression value) {
        return new JAXBElement<TPathExpression>(_TTwoChildrenExpressionAnnotationPath_QNAME, TPathExpression.class, TIfExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/odata/ns/edm", name = "Not", scope = TIfExpression.class)
    public JAXBElement<TOneChildExpression> createTIfExpressionNot(TOneChildExpression value) {
        return new JAXBElement<TOneChildExpression>(_TTwoChildrenExpressionNot_QNAME, TOneChildExpression.class, TIfExpression.class, value);
    }

}
