//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/odata/ns/edm",
        xmlns = {
        @XmlNs(namespaceURI = "http://docs.oasis-open.org/odata/ns/edmx", prefix = "edmx"),
                @XmlNs(namespaceURI = "http://docs.oasis-open.org/odata/ns/edm", prefix = "")
        }
        ,elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import javax.xml.bind.annotation.XmlNs;