//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;


import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="ComplexType" type="{http://docs.oasis-open.org/odata/ns/edm}TComplexType"/>
 *         &lt;element name="EntityType" type="{http://docs.oasis-open.org/odata/ns/edm}TEntityType"/>
 *         &lt;element name="TypeDefinition" type="{http://docs.oasis-open.org/odata/ns/edm}TTypeDefinition"/>
 *         &lt;element name="EnumType" type="{http://docs.oasis-open.org/odata/ns/edm}TEnumType"/>
 *         &lt;element name="Action" type="{http://docs.oasis-open.org/odata/ns/edm}TAction"/>
 *         &lt;element name="Function" type="{http://docs.oasis-open.org/odata/ns/edm}TFunction"/>
 *         &lt;element name="Term" type="{http://docs.oasis-open.org/odata/ns/edm}TTerm"/>
 *         &lt;element name="Annotations" type="{http://docs.oasis-open.org/odata/ns/edm}TAnnotations"/>
 *         &lt;element name="EntityContainer" type="{http://docs.oasis-open.org/odata/ns/edm}TEntityContainer"/>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation"/>
 *       &lt;/choice>
 *       &lt;attribute name="Namespace" use="required" type="{http://docs.oasis-open.org/odata/ns/edm}TNamespaceName" />
 *       &lt;attribute name="Alias" type="{http://docs.oasis-open.org/odata/ns/edm}TSimpleIdentifier" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Schema")
@XmlSeeAlso({TComplexType.class, TEntityType.class, TTypeDefinition.class, TEnumType.class, TAction.class, TFunction.class, TTerm.class, Annotation.class })
public class Schema {

    @XmlElement(name = "ComplexType", type = TComplexType.class)
    protected List<TComplexType>complexTypeList;
    @XmlElement(name = "EntityType", type = TEntityType.class)
    protected List<TEntityType> entityTypeList;
    @XmlElement(name = "TypeDefinition", type = TTypeDefinition.class)
    protected List<TTypeDefinition> typeDefinitionList;
    @XmlElement(name = "EnumType", type = TEnumType.class)
    protected List<TEnumType> enumTypeList;
    @XmlElement(name = "Action", type = TAction.class)
    protected List<TAction> actionList;
    @XmlElement(name = "Function", type = TFunction.class)
    protected List<TFunction> functionList;
    @XmlElement(name = "Term", type = TTerm.class)
    protected List<TTerm> termList;
    @XmlElement(name = "Annotations", type = TAnnotations.class)
    protected TAnnotations annotations;
    @XmlElement(name = "EntityContainer", type = TEntityContainer.class)
    protected TEntityContainer entityContainer;
    @XmlElement(name = "Annotation", type = Annotation.class)
    protected List<Annotation> annotationList;
    @XmlAttribute(name = "Namespace", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String namespace;
    @XmlAttribute(name = "Alias")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String alias;


    /**
     * Gets the value of the namespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * Sets the value of the namespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamespace(String value) {
        this.namespace = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    public List<TComplexType> getComplexTypeList() {
        return complexTypeList;
    }

    public void setComplexTypeList(List<TComplexType> complexTypeList) {
        this.complexTypeList = complexTypeList;
    }

    public List<TEntityType> getEntityTypeList() {
        return entityTypeList;
    }

    public void setEntityTypeList(List<TEntityType> entityTypeList) {
        this.entityTypeList = entityTypeList;
    }

    public List<TTypeDefinition> getTypeDefinitionList() {
        return typeDefinitionList;
    }

    public void setTypeDefinitionList(List<TTypeDefinition> typeDefinitionList) {
        this.typeDefinitionList = typeDefinitionList;
    }

    public List<TEnumType> getEnumTypeList() {
        return enumTypeList;
    }

    public void setEnumTypeList(List<TEnumType> enumTypeList) {
        this.enumTypeList = enumTypeList;
    }

    public List<TAction> getActionList() {
        return actionList;
    }

    public void setActionList(List<TAction> actionList) {
        this.actionList = actionList;
    }

    public List<TFunction> getFunctionList() {
        return functionList;
    }

    public void setFunctionList(List<TFunction> functionList) {
        this.functionList = functionList;
    }

    public List<TTerm> getTermList() {
        return termList;
    }

    public void setTermList(List<TTerm> termList) {
        this.termList = termList;
    }

    public TAnnotations getAnnotations() {
        return annotations;
    }

    public void setAnnotations(TAnnotations annotations) {
        this.annotations = annotations;
    }

    public TEntityContainer getEntityContainer() {
        return entityContainer;
    }

    public void setEntityContainer(TEntityContainer entityContainer) {
        this.entityContainer = entityContainer;
    }

    public List<Annotation> getAnnotationList() {
        return annotationList;
    }

    public void setAnnotationList(List<Annotation> annotationList) {
        this.annotationList = annotationList;
    }
}
