//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TApplyExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TApplyExpression">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://docs.oasis-open.org/odata/ns/edm}GExpression" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Function" type="{http://docs.oasis-open.org/odata/ns/edm}TClientFunction" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TApplyExpression", propOrder = {
    "annotation",
    "gExpression"
})
public class TApplyExpression {

    @XmlElement(name = "Annotation")
    protected List<Annotation> annotation;
    @XmlElementRefs({
        @XmlElementRef(name = "Bool", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Binary", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DateTimeOffset", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LabeledElementReference", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "If", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Not", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Ge", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Record", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "EnumMember", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "NavigationPropertyPath", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Guid", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Apply", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Eq", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Le", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Ne", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Duration", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "String", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "UrlRef", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Date", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Gt", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "And", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Null", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Float", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AnnotationPath", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Lt", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PropertyPath", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Decimal", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Int", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Collection", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Path", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Or", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Cast", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LabeledElement", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "IsOf", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TimeOfDay", namespace = "http://docs.oasis-open.org/odata/ns/edm", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> gExpression;
    @XmlAttribute(name = "Function")
    protected String function;

    /**
     * Gets the value of the annotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Annotation }
     * 
     * 
     */
    public List<Annotation> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<Annotation>();
        }
        return this.annotation;
    }

    /**
     * Gets the value of the gExpression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gExpression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TBoolConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TBinaryConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TDateTimeOffsetConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TLabeledElementReferenceExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TIfExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TRecordExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     * {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TGuidConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TApplyExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TDurationConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TStringConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TOneChildExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TDateConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TNullExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TFloatConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TDecimalConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TIntConstantExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TCollectionExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TPathExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTwoChildrenExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TLabeledElementExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TCastOrIsOfExpression }{@code >}
     * {@link JAXBElement }{@code <}{@link TTimeOfDayConstantExpression }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getGExpression() {
        if (gExpression == null) {
            gExpression = new ArrayList<JAXBElement<?>>();
        }
        return this.gExpression;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunction(String value) {
        this.function = value;
    }

}
