//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TCastOrIsOfExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TCastOrIsOfExpression">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://docs.oasis-open.org/odata/ns/edm}GExpression"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://docs.oasis-open.org/odata/ns/edm}TFacetAttributes"/>
 *       &lt;attribute name="Type" type="{http://docs.oasis-open.org/odata/ns/edm}TTypeName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TCastOrIsOfExpression", propOrder = {
    "annotation",
    "binaryElement",
    "boolElement",
    "dateElement",
    "dateTimeOffsetElement",
    "decimalElement",
    "durationElement",
    "enumMemberElement",
    "floatElement",
    "guidElement",
    "intElement",
    "stringElement",
    "timeOfDayElement",
    "annotationPathElement",
    "apply",
    "cast",
    "collection",
    "_if",
    "eq",
    "ne",
    "ge",
    "gt",
    "le",
    "lt",
    "and",
    "or",
    "not",
    "isOf",
    "labeledElement",
    "labeledElementReference",
    "_null",
    "navigationPropertyPathElement",
    "pathElement",
    "propertyPathElement",
    "record",
    "urlRefElement"
})
public class TCastOrIsOfExpression {

    @XmlElement(name = "Annotation")
    protected List<Annotation> annotation;
    @XmlElement(name = "Binary")
    protected TBinaryConstantExpression binaryElement;
    @XmlElement(name = "Bool")
    protected TBoolConstantExpression boolElement;
    @XmlElement(name = "Date")
    protected TDateConstantExpression dateElement;
    @XmlElement(name = "DateTimeOffset")
    protected TDateTimeOffsetConstantExpression dateTimeOffsetElement;
    @XmlElement(name = "Decimal")
    protected TDecimalConstantExpression decimalElement;
    @XmlElement(name = "Duration")
    protected TDurationConstantExpression durationElement;
    @XmlList
    @XmlElement(name = "EnumMember")
    protected List<String> enumMemberElement;
    @XmlElement(name = "Float")
    protected TFloatConstantExpression floatElement;
    @XmlElement(name = "Guid")
    protected TGuidConstantExpression guidElement;
    @XmlElement(name = "Int")
    protected TIntConstantExpression intElement;
    @XmlElement(name = "String")
    protected TStringConstantExpression stringElement;
    @XmlElement(name = "TimeOfDay")
    protected TTimeOfDayConstantExpression timeOfDayElement;
    @XmlElement(name = "AnnotationPath")
    protected TPathExpression annotationPathElement;
    @XmlElement(name = "Apply")
    protected TApplyExpression apply;
    @XmlElement(name = "Cast")
    protected TCastOrIsOfExpression cast;
    @XmlElement(name = "Collection")
    protected TCollectionExpression collection;
    @XmlElement(name = "If")
    protected TIfExpression _if;
    @XmlElement(name = "Eq")
    protected TTwoChildrenExpression eq;
    @XmlElement(name = "Ne")
    protected TTwoChildrenExpression ne;
    @XmlElement(name = "Ge")
    protected TTwoChildrenExpression ge;
    @XmlElement(name = "Gt")
    protected TTwoChildrenExpression gt;
    @XmlElement(name = "Le")
    protected TTwoChildrenExpression le;
    @XmlElement(name = "Lt")
    protected TTwoChildrenExpression lt;
    @XmlElement(name = "And")
    protected TTwoChildrenExpression and;
    @XmlElement(name = "Or")
    protected TTwoChildrenExpression or;
    @XmlElement(name = "Not")
    protected TOneChildExpression not;
    @XmlElement(name = "IsOf")
    protected TCastOrIsOfExpression isOf;
    @XmlElement(name = "LabeledElement")
    protected TLabeledElementExpression labeledElement;
    @XmlElement(name = "LabeledElementReference")
    protected TLabeledElementReferenceExpression labeledElementReference;
    @XmlElement(name = "Null")
    protected TNullExpression _null;
    @XmlElement(name = "NavigationPropertyPath")
    protected TPathExpression navigationPropertyPathElement;
    @XmlElement(name = "Path")
    protected TPathExpression pathElement;
    @XmlElement(name = "PropertyPath")
    protected TPathExpression propertyPathElement;
    @XmlElement(name = "Record")
    protected TRecordExpression record;
    @XmlElement(name = "UrlRef")
    protected TOneChildExpression urlRefElement;
    @XmlAttribute(name = "Type")
    protected List<String> type;
    @XmlAttribute(name = "MaxLength")
    protected String maxLength;
    @XmlAttribute(name = "Precision")
    protected BigInteger precision;
    @XmlAttribute(name = "Scale")
    protected String scale;
    @XmlAttribute(name = "SRID")
    protected String srid;

    /**
     * Gets the value of the annotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Annotation }
     * 
     * 
     */
    public List<Annotation> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<Annotation>();
        }
        return this.annotation;
    }

    /**
     * Gets the value of the binaryElement property.
     * 
     * @return
     *     possible object is
     *     {@link TBinaryConstantExpression }
     *     
     */
    public TBinaryConstantExpression getBinaryElement() {
        return binaryElement;
    }

    /**
     * Sets the value of the binaryElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBinaryConstantExpression }
     *     
     */
    public void setBinaryElement(TBinaryConstantExpression value) {
        this.binaryElement = value;
    }

    /**
     * Gets the value of the boolElement property.
     * 
     * @return
     *     possible object is
     *     {@link TBoolConstantExpression }
     *     
     */
    public TBoolConstantExpression getBoolElement() {
        return boolElement;
    }

    /**
     * Sets the value of the boolElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBoolConstantExpression }
     *     
     */
    public void setBoolElement(TBoolConstantExpression value) {
        this.boolElement = value;
    }

    /**
     * Gets the value of the dateElement property.
     * 
     * @return
     *     possible object is
     *     {@link TDateConstantExpression }
     *     
     */
    public TDateConstantExpression getDateElement() {
        return dateElement;
    }

    /**
     * Sets the value of the dateElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDateConstantExpression }
     *     
     */
    public void setDateElement(TDateConstantExpression value) {
        this.dateElement = value;
    }

    /**
     * Gets the value of the dateTimeOffsetElement property.
     * 
     * @return
     *     possible object is
     *     {@link TDateTimeOffsetConstantExpression }
     *     
     */
    public TDateTimeOffsetConstantExpression getDateTimeOffsetElement() {
        return dateTimeOffsetElement;
    }

    /**
     * Sets the value of the dateTimeOffsetElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDateTimeOffsetConstantExpression }
     *     
     */
    public void setDateTimeOffsetElement(TDateTimeOffsetConstantExpression value) {
        this.dateTimeOffsetElement = value;
    }

    /**
     * Gets the value of the decimalElement property.
     * 
     * @return
     *     possible object is
     *     {@link TDecimalConstantExpression }
     *     
     */
    public TDecimalConstantExpression getDecimalElement() {
        return decimalElement;
    }

    /**
     * Sets the value of the decimalElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDecimalConstantExpression }
     *     
     */
    public void setDecimalElement(TDecimalConstantExpression value) {
        this.decimalElement = value;
    }

    /**
     * Gets the value of the durationElement property.
     * 
     * @return
     *     possible object is
     *     {@link TDurationConstantExpression }
     *     
     */
    public TDurationConstantExpression getDurationElement() {
        return durationElement;
    }

    /**
     * Sets the value of the durationElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDurationConstantExpression }
     *     
     */
    public void setDurationElement(TDurationConstantExpression value) {
        this.durationElement = value;
    }

    /**
     * Gets the value of the enumMemberElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumMemberElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnumMemberElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEnumMemberElement() {
        if (enumMemberElement == null) {
            enumMemberElement = new ArrayList<String>();
        }
        return this.enumMemberElement;
    }

    /**
     * Gets the value of the floatElement property.
     * 
     * @return
     *     possible object is
     *     {@link TFloatConstantExpression }
     *     
     */
    public TFloatConstantExpression getFloatElement() {
        return floatElement;
    }

    /**
     * Sets the value of the floatElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFloatConstantExpression }
     *     
     */
    public void setFloatElement(TFloatConstantExpression value) {
        this.floatElement = value;
    }

    /**
     * Gets the value of the guidElement property.
     * 
     * @return
     *     possible object is
     *     {@link TGuidConstantExpression }
     *     
     */
    public TGuidConstantExpression getGuidElement() {
        return guidElement;
    }

    /**
     * Sets the value of the guidElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TGuidConstantExpression }
     *     
     */
    public void setGuidElement(TGuidConstantExpression value) {
        this.guidElement = value;
    }

    /**
     * Gets the value of the intElement property.
     * 
     * @return
     *     possible object is
     *     {@link TIntConstantExpression }
     *     
     */
    public TIntConstantExpression getIntElement() {
        return intElement;
    }

    /**
     * Sets the value of the intElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIntConstantExpression }
     *     
     */
    public void setIntElement(TIntConstantExpression value) {
        this.intElement = value;
    }

    /**
     * Gets the value of the stringElement property.
     * 
     * @return
     *     possible object is
     *     {@link TStringConstantExpression }
     *     
     */
    public TStringConstantExpression getStringElement() {
        return stringElement;
    }

    /**
     * Sets the value of the stringElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStringConstantExpression }
     *     
     */
    public void setStringElement(TStringConstantExpression value) {
        this.stringElement = value;
    }

    /**
     * Gets the value of the timeOfDayElement property.
     * 
     * @return
     *     possible object is
     *     {@link TTimeOfDayConstantExpression }
     *     
     */
    public TTimeOfDayConstantExpression getTimeOfDayElement() {
        return timeOfDayElement;
    }

    /**
     * Sets the value of the timeOfDayElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTimeOfDayConstantExpression }
     *     
     */
    public void setTimeOfDayElement(TTimeOfDayConstantExpression value) {
        this.timeOfDayElement = value;
    }

    /**
     * Gets the value of the annotationPathElement property.
     * 
     * @return
     *     possible object is
     *     {@link TPathExpression }
     *     
     */
    public TPathExpression getAnnotationPathElement() {
        return annotationPathElement;
    }

    /**
     * Sets the value of the annotationPathElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPathExpression }
     *     
     */
    public void setAnnotationPathElement(TPathExpression value) {
        this.annotationPathElement = value;
    }

    /**
     * Gets the value of the apply property.
     * 
     * @return
     *     possible object is
     *     {@link TApplyExpression }
     *     
     */
    public TApplyExpression getApply() {
        return apply;
    }

    /**
     * Sets the value of the apply property.
     * 
     * @param value
     *     allowed object is
     *     {@link TApplyExpression }
     *     
     */
    public void setApply(TApplyExpression value) {
        this.apply = value;
    }

    /**
     * Gets the value of the cast property.
     * 
     * @return
     *     possible object is
     *     {@link TCastOrIsOfExpression }
     *     
     */
    public TCastOrIsOfExpression getCast() {
        return cast;
    }

    /**
     * Sets the value of the cast property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCastOrIsOfExpression }
     *     
     */
    public void setCast(TCastOrIsOfExpression value) {
        this.cast = value;
    }

    /**
     * Gets the value of the collection property.
     * 
     * @return
     *     possible object is
     *     {@link TCollectionExpression }
     *     
     */
    public TCollectionExpression getCollection() {
        return collection;
    }

    /**
     * Sets the value of the collection property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCollectionExpression }
     *     
     */
    public void setCollection(TCollectionExpression value) {
        this.collection = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link TIfExpression }
     *     
     */
    public TIfExpression getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIfExpression }
     *     
     */
    public void setIf(TIfExpression value) {
        this._if = value;
    }

    /**
     * Gets the value of the eq property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getEq() {
        return eq;
    }

    /**
     * Sets the value of the eq property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setEq(TTwoChildrenExpression value) {
        this.eq = value;
    }

    /**
     * Gets the value of the ne property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getNe() {
        return ne;
    }

    /**
     * Sets the value of the ne property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setNe(TTwoChildrenExpression value) {
        this.ne = value;
    }

    /**
     * Gets the value of the ge property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getGe() {
        return ge;
    }

    /**
     * Sets the value of the ge property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setGe(TTwoChildrenExpression value) {
        this.ge = value;
    }

    /**
     * Gets the value of the gt property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getGt() {
        return gt;
    }

    /**
     * Sets the value of the gt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setGt(TTwoChildrenExpression value) {
        this.gt = value;
    }

    /**
     * Gets the value of the le property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getLe() {
        return le;
    }

    /**
     * Sets the value of the le property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setLe(TTwoChildrenExpression value) {
        this.le = value;
    }

    /**
     * Gets the value of the lt property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getLt() {
        return lt;
    }

    /**
     * Sets the value of the lt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setLt(TTwoChildrenExpression value) {
        this.lt = value;
    }

    /**
     * Gets the value of the and property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getAnd() {
        return and;
    }

    /**
     * Sets the value of the and property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setAnd(TTwoChildrenExpression value) {
        this.and = value;
    }

    /**
     * Gets the value of the or property.
     * 
     * @return
     *     possible object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public TTwoChildrenExpression getOr() {
        return or;
    }

    /**
     * Sets the value of the or property.
     * 
     * @param value
     *     allowed object is
     *     {@link TTwoChildrenExpression }
     *     
     */
    public void setOr(TTwoChildrenExpression value) {
        this.or = value;
    }

    /**
     * Gets the value of the not property.
     * 
     * @return
     *     possible object is
     *     {@link TOneChildExpression }
     *     
     */
    public TOneChildExpression getNot() {
        return not;
    }

    /**
     * Sets the value of the not property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOneChildExpression }
     *     
     */
    public void setNot(TOneChildExpression value) {
        this.not = value;
    }

    /**
     * Gets the value of the isOf property.
     * 
     * @return
     *     possible object is
     *     {@link TCastOrIsOfExpression }
     *     
     */
    public TCastOrIsOfExpression getIsOf() {
        return isOf;
    }

    /**
     * Sets the value of the isOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCastOrIsOfExpression }
     *     
     */
    public void setIsOf(TCastOrIsOfExpression value) {
        this.isOf = value;
    }

    /**
     * Gets the value of the labeledElement property.
     * 
     * @return
     *     possible object is
     *     {@link TLabeledElementExpression }
     *     
     */
    public TLabeledElementExpression getLabeledElement() {
        return labeledElement;
    }

    /**
     * Sets the value of the labeledElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLabeledElementExpression }
     *     
     */
    public void setLabeledElement(TLabeledElementExpression value) {
        this.labeledElement = value;
    }

    /**
     * Gets the value of the labeledElementReference property.
     * 
     * @return
     *     possible object is
     *     {@link TLabeledElementReferenceExpression }
     *     
     */
    public TLabeledElementReferenceExpression getLabeledElementReference() {
        return labeledElementReference;
    }

    /**
     * Sets the value of the labeledElementReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLabeledElementReferenceExpression }
     *     
     */
    public void setLabeledElementReference(TLabeledElementReferenceExpression value) {
        this.labeledElementReference = value;
    }

    /**
     * Gets the value of the null property.
     * 
     * @return
     *     possible object is
     *     {@link TNullExpression }
     *     
     */
    public TNullExpression getNull() {
        return _null;
    }

    /**
     * Sets the value of the null property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNullExpression }
     *     
     */
    public void setNull(TNullExpression value) {
        this._null = value;
    }

    /**
     * Gets the value of the navigationPropertyPathElement property.
     * 
     * @return
     *     possible object is
     *     {@link TPathExpression }
     *     
     */
    public TPathExpression getNavigationPropertyPathElement() {
        return navigationPropertyPathElement;
    }

    /**
     * Sets the value of the navigationPropertyPathElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPathExpression }
     *     
     */
    public void setNavigationPropertyPathElement(TPathExpression value) {
        this.navigationPropertyPathElement = value;
    }

    /**
     * Gets the value of the pathElement property.
     * 
     * @return
     *     possible object is
     *     {@link TPathExpression }
     *     
     */
    public TPathExpression getPathElement() {
        return pathElement;
    }

    /**
     * Sets the value of the pathElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPathExpression }
     *     
     */
    public void setPathElement(TPathExpression value) {
        this.pathElement = value;
    }

    /**
     * Gets the value of the propertyPathElement property.
     * 
     * @return
     *     possible object is
     *     {@link TPathExpression }
     *     
     */
    public TPathExpression getPropertyPathElement() {
        return propertyPathElement;
    }

    /**
     * Sets the value of the propertyPathElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPathExpression }
     *     
     */
    public void setPropertyPathElement(TPathExpression value) {
        this.propertyPathElement = value;
    }

    /**
     * Gets the value of the record property.
     * 
     * @return
     *     possible object is
     *     {@link TRecordExpression }
     *     
     */
    public TRecordExpression getRecord() {
        return record;
    }

    /**
     * Sets the value of the record property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRecordExpression }
     *     
     */
    public void setRecord(TRecordExpression value) {
        this.record = value;
    }

    /**
     * Gets the value of the urlRefElement property.
     * 
     * @return
     *     possible object is
     *     {@link TOneChildExpression }
     *     
     */
    public TOneChildExpression getUrlRefElement() {
        return urlRefElement;
    }

    /**
     * Sets the value of the urlRefElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link TOneChildExpression }
     *     
     */
    public void setUrlRefElement(TOneChildExpression value) {
        this.urlRefElement = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getType() {
        if (type == null) {
            type = new ArrayList<String>();
        }
        return this.type;
    }

    /**
     * Gets the value of the maxLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxLength() {
        return maxLength;
    }

    /**
     * Sets the value of the maxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxLength(String value) {
        this.maxLength = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrecision(BigInteger value) {
        this.precision = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScale(String value) {
        this.scale = value;
    }

    /**
     * Gets the value of the srid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRID() {
        return srid;
    }

    /**
     * Sets the value of the srid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRID(String value) {
        this.srid = value;
    }

}
