//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Property" type="{http://docs.oasis-open.org/odata/ns/edm}TProperty"/>
 *         &lt;element name="NavigationProperty" type="{http://docs.oasis-open.org/odata/ns/edm}TNavigationProperty"/>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://docs.oasis-open.org/odata/ns/edm}TDerivableTypeAttributes"/>
 *       &lt;attribute name="OpenType" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TComplexType")
public class TComplexType {

    @XmlElement(name = "Property", type = TProperty.class)
    protected List<TProperty> propertyList;
    @XmlElement(name = "NavigationProperty", type = TNavigationProperty.class)
    protected List<TNavigationProperty> navigationPropertyList;
    @XmlElement(name = "Annotation", type = Annotation.class)
    protected List<Annotation> annotationList;
    @XmlAttribute(name = "OpenType")
    protected Boolean openType;
    @XmlAttribute(name = "BaseType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String baseType;
    @XmlAttribute(name = "Abstract")
    protected Boolean _abstract;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;


    /**
     * Gets the value of the openType property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOpenType() {
        if (openType == null) {
            return false;
        } else {
            return openType;
        }
    }

    /**
     * Sets the value of the openType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOpenType(Boolean value) {
        this.openType = value;
    }

    /**
     * Gets the value of the baseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseType() {
        return baseType;
    }

    /**
     * Sets the value of the baseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseType(String value) {
        this.baseType = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAbstract() {
        if (_abstract == null) {
            return false;
        } else {
            return _abstract;
        }
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbstract(Boolean value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public List<TProperty> getPropertyList() {
        return propertyList;
    }

    public void setPropertyList(List<TProperty> propertyList) {
        this.propertyList = propertyList;
    }

    public List<TNavigationProperty> getNavigationPropertyList() {
        return navigationPropertyList;
    }

    public void setNavigationPropertyList(List<TNavigationProperty> navigationPropertyList) {
        this.navigationPropertyList = navigationPropertyList;
    }

    public List<Annotation> getAnnotationList() {
        return annotationList;
    }

    public void setAnnotationList(List<Annotation> annotationList) {
        this.annotationList = annotationList;
    }
}
