//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TEntitySet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEntitySet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="NavigationPropertyBinding" type="{http://docs.oasis-open.org/odata/ns/edm}TNavigationPropertyBinding"/>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://docs.oasis-open.org/odata/ns/edm}TEntitySetAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEntitySet")
@XmlSeeAlso({TNavigationPropertyBinding.class, Annotation.class})
public class TEntitySet {

    @XmlElement(name = "NavigationPropertyBinding", type = TNavigationPropertyBinding.class)
    List<TNavigationPropertyBinding> navigationPropertyBindingList;
    @XmlElement(name = "Annotation", type = Annotation.class)
    List<Annotation> annotationList;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "EntityType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String entityType;
    @XmlAttribute(name = "IncludeInServiceDocument")
    protected Boolean includeInServiceDocument;



    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the includeInServiceDocument property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIncludeInServiceDocument() {
        if (includeInServiceDocument == null) {
            return true;
        } else {
            return includeInServiceDocument;
        }
    }

    /**
     * Sets the value of the includeInServiceDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeInServiceDocument(Boolean value) {
        this.includeInServiceDocument = value;
    }

    public List<TNavigationPropertyBinding> getNavigationPropertyBindingList() {
        return navigationPropertyBindingList;
    }

    public void setNavigationPropertyBindingList(List<TNavigationPropertyBinding> navigationPropertyBindingList) {
        this.navigationPropertyBindingList = navigationPropertyBindingList;
    }

    public List<Annotation> getAnnotationList() {
        return annotationList;
    }

    public void setAnnotationList(List<Annotation> annotationList) {
        this.annotationList = annotationList;
    }
}
