//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TEntityContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEntityContainer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="EntitySet" type="{http://docs.oasis-open.org/odata/ns/edm}TEntitySet"/>
 *         &lt;element name="ActionImport" type="{http://docs.oasis-open.org/odata/ns/edm}TActionImport"/>
 *         &lt;element name="FunctionImport" type="{http://docs.oasis-open.org/odata/ns/edm}TFunctionImport"/>
 *         &lt;element name="Singleton" type="{http://docs.oasis-open.org/odata/ns/edm}TSingleton"/>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation"/>
 *       &lt;/choice>
 *       &lt;attribute name="Name" use="required" type="{http://docs.oasis-open.org/odata/ns/edm}TSimpleIdentifier" />
 *       &lt;attribute name="Extends" type="{http://docs.oasis-open.org/odata/ns/edm}TQualifiedName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEntityContainer")
@XmlSeeAlso({TEntitySet.class, TActionImport.class, TFunctionImport.class, TSingleton.class, Annotation.class })
public class TEntityContainer {

    @XmlElement(name = "EntitySet", type = TEntitySet.class)
    protected List<TEntitySet> entitySetList;
    @XmlElement(name = "ActionImport", type = TActionImport.class)
    protected List<TActionImport> actionImportList;
    @XmlElement(name = "FunctionImport", type = TFunctionImport.class)
    protected List<TFunctionImport> functionImportList;
    @XmlElement(name = "Singleton", type = TSingleton.class)
    protected List<TSingleton> singletonList;
    @XmlElement(name = "Annotation", type = Annotation.class)
    protected List<Annotation> annotationList;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "Extends")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String _extends;



    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtends() {
        return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtends(String value) {
        this._extends = value;
    }

    public List<TEntitySet> getEntitySetList() {
        return entitySetList;
    }

    public void setEntitySetList(List<TEntitySet> entitySetList) {
        this.entitySetList = entitySetList;
    }

    public List<TActionImport> getActionImportList() {
        return actionImportList;
    }

    public void setActionImportList(List<TActionImport> actionImportList) {
        this.actionImportList = actionImportList;
    }

    public List<TFunctionImport> getFunctionImportList() {
        return functionImportList;
    }

    public void setFunctionImportList(List<TFunctionImport> functionImportList) {
        this.functionImportList = functionImportList;
    }

    public List<TSingleton> getSingletonList() {
        return singletonList;
    }

    public void setSingletonList(List<TSingleton> singletonList) {
        this.singletonList = singletonList;
    }

    public List<Annotation> getAnnotationList() {
        return annotationList;
    }

    public void setAnnotationList(List<Annotation> annotationList) {
        this.annotationList = annotationList;
    }
}
