//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TEnumType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TEnumType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Member" type="{http://docs.oasis-open.org/odata/ns/edm}TEnumTypeMember"/>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://docs.oasis-open.org/odata/ns/edm}TTypeAttributes"/>
 *       &lt;attribute name="IsFlags" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="UnderlyingType" type="{http://docs.oasis-open.org/odata/ns/edm}TTypeName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TEnumType")
@XmlSeeAlso({TEnumTypeMember.class, Annotation.class})
public class TEnumType {


    @XmlElement(name = "Member", type = TEnumTypeMember.class)
    protected List<TEnumTypeMember> memberList;
    @XmlElement(name = "Annotation", type = Annotation.class)
    protected List<Annotation> annotationList;
    @XmlAttribute(name = "IsFlags")
    protected Boolean isFlags;
    @XmlAttribute(name = "UnderlyingType")
    protected List<String> underlyingType;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;



    /**
     * Gets the value of the isFlags property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFlags() {
        return isFlags;
    }

    /**
     * Sets the value of the isFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFlags(Boolean value) {
        this.isFlags = value;
    }

    /**
     * Gets the value of the underlyingType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the underlyingType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnderlyingType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUnderlyingType() {
        if (underlyingType == null) {
            underlyingType = new ArrayList<String>();
        }
        return this.underlyingType;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public List<TEnumTypeMember> getMemberList() {
        return memberList;
    }

    public void setMemberList(List<TEnumTypeMember> memberList) {
        this.memberList = memberList;
    }

    public List<Annotation> getAnnotationList() {
        return annotationList;
    }

    public void setAnnotationList(List<Annotation> annotationList) {
        this.annotationList = annotationList;
    }
}
