//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TFunction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TFunction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="Parameter" type="{http://docs.oasis-open.org/odata/ns/edm}TActionFunctionParameter"/>
 *           &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation"/>
 *         &lt;/choice>
 *         &lt;element name="ReturnType" type="{http://docs.oasis-open.org/odata/ns/edm}TActionFunctionReturnType"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://docs.oasis-open.org/odata/ns/edm}TFunctionAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TFunction")
@XmlSeeAlso({TActionFunctionParameter.class, Annotation.class })
public class TFunction {

    @XmlElement(name = "Parameter", type = TActionFunctionParameter.class)
    protected List<TActionFunctionParameter> parameterList;
    @XmlElement(name = "Annotation", type = Annotation.class)
    protected List<Annotation> annotationList;
    @XmlElement(name = "ReturnType", required = true)
    protected TActionFunctionReturnType returnType;
    @XmlAttribute(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "EntitySetPath")
    protected String entitySetPath;
    @XmlAttribute(name = "IsBound")
    protected Boolean isBound;
    @XmlAttribute(name = "IsComposable")
    protected Boolean isComposable;



    /**
     * Gets the value of the returnType property.
     * 
     * @return
     *     possible object is
     *     {@link TActionFunctionReturnType }
     *     
     */
    public TActionFunctionReturnType getReturnType() {
        return returnType;
    }

    /**
     * Sets the value of the returnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TActionFunctionReturnType }
     *     
     */
    public void setReturnType(TActionFunctionReturnType value) {
        this.returnType = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the entitySetPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntitySetPath() {
        return entitySetPath;
    }

    /**
     * Sets the value of the entitySetPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntitySetPath(String value) {
        this.entitySetPath = value;
    }

    /**
     * Gets the value of the isBound property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsBound() {
        if (isBound == null) {
            return false;
        } else {
            return isBound;
        }
    }

    /**
     * Sets the value of the isBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBound(Boolean value) {
        this.isBound = value;
    }

    /**
     * Gets the value of the isComposable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsComposable() {
        if (isComposable == null) {
            return false;
        } else {
            return isComposable;
        }
    }

    /**
     * Sets the value of the isComposable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsComposable(Boolean value) {
        this.isComposable = value;
    }

    public List<TActionFunctionParameter> getParameterList() {
        return parameterList;
    }

    public void setParameterList(List<TActionFunctionParameter> parameterList) {
        this.parameterList = parameterList;
    }

    public List<Annotation> getAnnotationList() {
        return annotationList;
    }

    public void setAnnotationList(List<Annotation> annotationList) {
        this.annotationList = annotationList;
    }
}
