//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 04:17:04 PM IST 
//


package com.ifsworld.rnd.intern.openapi.generator.metadata_parser.edm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TRecordExpression complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TRecordExpression">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="PropertyValue" type="{http://docs.oasis-open.org/odata/ns/edm}TPropertyValue"/>
 *         &lt;element ref="{http://docs.oasis-open.org/odata/ns/edm}Annotation"/>
 *       &lt;/choice>
 *       &lt;attribute name="Type" type="{http://docs.oasis-open.org/odata/ns/edm}TQualifiedName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRecordExpression")
@XmlSeeAlso({TPropertyValue.class, Annotation.class})
public class TRecordExpression {

    @XmlElement(name = "PropertyValue", type = TPropertyValue.class)
    protected List<TPropertyValue> propertyValueList;
    @XmlElement(name = "Annotation", type = Annotation.class)
    protected List<Annotation> annotationList;
    @XmlAttribute(name = "Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;



    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public List<TPropertyValue> getPropertyValueList() {
        return propertyValueList;
    }

    public void setPropertyValueList(List<TPropertyValue> propertyValueList) {
        this.propertyValueList = propertyValueList;
    }

    public List<Annotation> getAnnotationList() {
        return annotationList;
    }

    public void setAnnotationList(List<Annotation> annotationList) {
        this.annotationList = annotationList;
    }
}
